dbfilename redis_cache.rdb
dir /mnt/d/frappe/new-app/config/pids
pidfile /mnt/d/frappe/new-app/config/pids/redis_cache.pid
bind 127.0.0.1
port 13000
maxmemory 388mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /mnt/d/frappe/new-app/config/redis_cache.acl
